#Setup LAMP Stack
version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies/main.yml
      timeout: 300
      
    - location: scripts/start_server.sh
      timeout: 300
      


    
